# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

for sqrt_value in generator:
    print(sqrt_value)

print("\n\nSum of the outputs of the generator for limit = 5:")
print(sum(list(square_root_generator(5))))

print("\n\nThe 13th number yielded:")
print(list(square_root_generator(13))[12])

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979


Sum of the outputs of the generator for limit = 5:
8.382332347441762


The 13th number yielded = 5:

3.605551275463989

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

In [ ]:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
    print(person)


def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
    print(person)

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:

In [ ]:
#Install the dependencies
%%capture
!pip install dlt[duckdb]

In [ ]:
# to do: homework :)
import dlt

# define the connection to load to.
# We now use duckdb, but you can switch to Bigquery later
generators_pipeline = dlt.pipeline(destination='duckdb', dataset_name='generators')


# we can load any generator to a table at the pipeline destnation as follows:
info = generators_pipeline.run(people_1(),
  table_name="people",
  write_disposition="replace"
)

# the outcome metadata is returned by the load and we can inspect it by printing it.
print(info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.41 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708534423.646375 is LOADED and contains no failed jobs

#Quetion 3 : Append

In [ ]:
# Let's add the data into the previous dataset
info = generators_pipeline.run(people_2(),
  table_name="people",
  write_disposition="append"
)

# the outcome metadata is returned by the load and we can inspect it by printing it.
print(info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.25 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708534427.5748277 is LOADED and contains no failed jobs

In [ ]:
import duckdb

conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# let's see the tables
conn.sql(f"SET search_path = '{generators_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))

# and the data

print("\n\n\n people table below:")

people_added = conn.sql("SELECT * FROM people").df()
display(people_added)

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
└─────────────────────┘

 people table below:

    id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A   1708534423.646375  5ZLGowywJOTY7g       None
1    2  Person_2   27  City_A   1708534423.646375  zZQpsjoSB4eynA       None
2    3  Person_3   28  City_A   1708534423.646375  i/fuPR/HPdB0CA       None
3    4  Person_4   29  City_A   1708534423.646375  q6K721Lz9ciXaQ       None
4    5  Person_5   30  City_A   1708534423.646375  qRssgir8GjMfiQ       None
5    3  Person_3   33  City_B  1708534427.5748277  ASpF5w+F1T4z8Q      Job_3
6    4  Person_4   34  City_B  1708534427.5748277  SyzckOn5lufSCA      Job_4
7    5  Person_5   35  City_B  1708534427.5748277  TQZYCH5qpv/U9Q      Job_5
8    6  Person_6   36  City_B  1708534427.5748277  yhGKlm5gw5GWOA      Job_6
9    7  Person_7   37  City_B  1708534427.5748277  D3QgyuvFUPIogQ      Job_7
10   8  Person_8   38  City_B  1708534427.5748277  g4iXl1+p8Mw5jQ      Job_8

In [ ]:
# print the result of Question 3
print("After appending the 2 generators. After correctly appending the data, the sum of all ages of people is:")
conn.sql("SELECT SUM(age) FROM people")

After appending the 2 generators. After correctly appending the data, the sum of all ages of people is:

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      353 │
└──────────┘

# Question 4. Merge

In [ ]:
# Let's merge the 2 generators
info = generators_pipeline.run(people_2,
  table_name="people",
  write_disposition="merge",
  primary_key='ID'
)

print(info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.33 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708534438.2330604 is LOADED and contains no failed jobs

In [ ]:
import duckdb

conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# let's see the tables
conn.sql(f"SET search_path = '{generators_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))

# and the data

print("\n\n\n people table below:")

people_merged = conn.sql("SELECT * FROM people").df()
display(people_merged)

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
└─────────────────────┘

 people table below:

   id      name  age    city        _dlt_load_id         _dlt_id occupation
0   1  Person_1   26  City_A   1708534423.646375  5ZLGowywJOTY7g       None
1   2  Person_2   27  City_A   1708534423.646375  zZQpsjoSB4eynA       None
2   5  Person_5   35  City_B  1708534438.2330604  H+c5fyfVwKGqXg      Job_5
3   7  Person_7   37  City_B  1708534438.2330604  pxETGrDFjqhsJg      Job_7
4   4  Person_4   34  City_B  1708534438.2330604  8DLdb87sD7j/uw      Job_4
5   8  Person_8   38  City_B  1708534438.2330604  TjbUf4JOuo5yKg      Job_8
6   3  Person_3   33  City_B  1708534438.2330604  dIJjB6KV3iz0Sw      Job_3
7   6  Person_6   36  City_B  1708534438.2330604  W10YFgEQOpVXZw      Job_6

In [ ]:
# print the result of Question 4
print("After merge the 2 generators using the ID column. The sum of ages of all the people loaded is:")
conn.sql("SELECT SUM(age) FROM people")

After merge the 2 generators using the ID column. The sum of ages of all the people loaded is:

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      266 │
└──────────┘

Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX